// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataitem.proto

package com.xzj.encode;

public final class DataMsg {
  private DataMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xzj.encode.DataItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 oddA = 1;</code>
     * @return The oddA.
     */
    long getOddA();

    /**
     * <code>int64 evenA = 2;</code>
     * @return The evenA.
     */
    long getEvenA();

    /**
     * <code>int32 oddB = 3;</code>
     * @return The oddB.
     */
    int getOddB();

    /**
     * <code>int32 evenB = 4;</code>
     * @return The evenB.
     */
    int getEvenB();

    /**
     * <code>float small = 5;</code>
     * @return The small.
     */
    float getSmall();

    /**
     * <code>float big = 6;</code>
     * @return The big.
     */
    float getBig();

    /**
     * <code>string short = 7;</code>
     * @return The short.
     */
    String getShort();
    /**
     * <code>string short = 7;</code>
     * @return The bytes for short.
     */
    com.google.protobuf.ByteString
        getShortBytes();

    /**
     * <code>string long = 8;</code>
     * @return The long.
     */
    String getLong();
    /**
     * <code>string long = 8;</code>
     * @return The bytes for long.
     */
    com.google.protobuf.ByteString
        getLongBytes();
  }
  /**
   * Protobuf type {@code com.xzj.encode.DataItem}
   */
  public  static final class DataItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xzj.encode.DataItem)
      DataItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataItem.newBuilder() to construct.
    private DataItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataItem() {
      short_ = "";
      long_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataItem();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              oddA_ = input.readInt64();
              break;
            }
            case 16: {

              evenA_ = input.readInt64();
              break;
            }
            case 24: {

              oddB_ = input.readInt32();
              break;
            }
            case 32: {

              evenB_ = input.readInt32();
              break;
            }
            case 45: {

              small_ = input.readFloat();
              break;
            }
            case 53: {

              big_ = input.readFloat();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              short_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              long_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataMsg.internal_static_com_xzj_encode_DataItem_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataMsg.internal_static_com_xzj_encode_DataItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataItem.class, Builder.class);
    }

    public static final int ODDA_FIELD_NUMBER = 1;
    private long oddA_;
    /**
     * <code>int64 oddA = 1;</code>
     * @return The oddA.
     */
    public long getOddA() {
      return oddA_;
    }

    public static final int EVENA_FIELD_NUMBER = 2;
    private long evenA_;
    /**
     * <code>int64 evenA = 2;</code>
     * @return The evenA.
     */
    public long getEvenA() {
      return evenA_;
    }

    public static final int ODDB_FIELD_NUMBER = 3;
    private int oddB_;
    /**
     * <code>int32 oddB = 3;</code>
     * @return The oddB.
     */
    public int getOddB() {
      return oddB_;
    }

    public static final int EVENB_FIELD_NUMBER = 4;
    private int evenB_;
    /**
     * <code>int32 evenB = 4;</code>
     * @return The evenB.
     */
    public int getEvenB() {
      return evenB_;
    }

    public static final int SMALL_FIELD_NUMBER = 5;
    private float small_;
    /**
     * <code>float small = 5;</code>
     * @return The small.
     */
    public float getSmall() {
      return small_;
    }

    public static final int BIG_FIELD_NUMBER = 6;
    private float big_;
    /**
     * <code>float big = 6;</code>
     * @return The big.
     */
    public float getBig() {
      return big_;
    }

    public static final int SHORT_FIELD_NUMBER = 7;
    private volatile Object short_;
    /**
     * <code>string short = 7;</code>
     * @return The short.
     */
    public String getShort() {
      Object ref = short_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        short_ = s;
        return s;
      }
    }
    /**
     * <code>string short = 7;</code>
     * @return The bytes for short.
     */
    public com.google.protobuf.ByteString
        getShortBytes() {
      Object ref = short_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        short_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONG_FIELD_NUMBER = 8;
    private volatile Object long_;
    /**
     * <code>string long = 8;</code>
     * @return The long.
     */
    public String getLong() {
      Object ref = long_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        long_ = s;
        return s;
      }
    }
    /**
     * <code>string long = 8;</code>
     * @return The bytes for long.
     */
    public com.google.protobuf.ByteString
        getLongBytes() {
      Object ref = long_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        long_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (oddA_ != 0L) {
        output.writeInt64(1, oddA_);
      }
      if (evenA_ != 0L) {
        output.writeInt64(2, evenA_);
      }
      if (oddB_ != 0) {
        output.writeInt32(3, oddB_);
      }
      if (evenB_ != 0) {
        output.writeInt32(4, evenB_);
      }
      if (small_ != 0F) {
        output.writeFloat(5, small_);
      }
      if (big_ != 0F) {
        output.writeFloat(6, big_);
      }
      if (!getShortBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, short_);
      }
      if (!getLongBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, long_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (oddA_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, oddA_);
      }
      if (evenA_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, evenA_);
      }
      if (oddB_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, oddB_);
      }
      if (evenB_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, evenB_);
      }
      if (small_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, small_);
      }
      if (big_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, big_);
      }
      if (!getShortBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, short_);
      }
      if (!getLongBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, long_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataItem)) {
        return super.equals(obj);
      }
      DataItem other = (DataItem) obj;

      if (getOddA()
          != other.getOddA()) return false;
      if (getEvenA()
          != other.getEvenA()) return false;
      if (getOddB()
          != other.getOddB()) return false;
      if (getEvenB()
          != other.getEvenB()) return false;
      if (Float.floatToIntBits(getSmall())
          != Float.floatToIntBits(
              other.getSmall())) return false;
      if (Float.floatToIntBits(getBig())
          != Float.floatToIntBits(
              other.getBig())) return false;
      if (!getShort()
          .equals(other.getShort())) return false;
      if (!getLong()
          .equals(other.getLong())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ODDA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOddA());
      hash = (37 * hash) + EVENA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEvenA());
      hash = (37 * hash) + ODDB_FIELD_NUMBER;
      hash = (53 * hash) + getOddB();
      hash = (37 * hash) + EVENB_FIELD_NUMBER;
      hash = (53 * hash) + getEvenB();
      hash = (37 * hash) + SMALL_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getSmall());
      hash = (37 * hash) + BIG_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getBig());
      hash = (37 * hash) + SHORT_FIELD_NUMBER;
      hash = (53 * hash) + getShort().hashCode();
      hash = (37 * hash) + LONG_FIELD_NUMBER;
      hash = (53 * hash) + getLong().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xzj.encode.DataItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xzj.encode.DataItem)
        DataItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataMsg.internal_static_com_xzj_encode_DataItem_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataMsg.internal_static_com_xzj_encode_DataItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataItem.class, Builder.class);
      }

      // Construct using com.xzj.encode.DataMsg.DataItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        oddA_ = 0L;

        evenA_ = 0L;

        oddB_ = 0;

        evenB_ = 0;

        small_ = 0F;

        big_ = 0F;

        short_ = "";

        long_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataMsg.internal_static_com_xzj_encode_DataItem_descriptor;
      }

      @Override
      public DataItem getDefaultInstanceForType() {
        return DataItem.getDefaultInstance();
      }

      @Override
      public DataItem build() {
        DataItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DataItem buildPartial() {
        DataItem result = new DataItem(this);
        result.oddA_ = oddA_;
        result.evenA_ = evenA_;
        result.oddB_ = oddB_;
        result.evenB_ = evenB_;
        result.small_ = small_;
        result.big_ = big_;
        result.short_ = short_;
        result.long_ = long_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataItem) {
          return mergeFrom((DataItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataItem other) {
        if (other == DataItem.getDefaultInstance()) return this;
        if (other.getOddA() != 0L) {
          setOddA(other.getOddA());
        }
        if (other.getEvenA() != 0L) {
          setEvenA(other.getEvenA());
        }
        if (other.getOddB() != 0) {
          setOddB(other.getOddB());
        }
        if (other.getEvenB() != 0) {
          setEvenB(other.getEvenB());
        }
        if (other.getSmall() != 0F) {
          setSmall(other.getSmall());
        }
        if (other.getBig() != 0F) {
          setBig(other.getBig());
        }
        if (!other.getShort().isEmpty()) {
          short_ = other.short_;
          onChanged();
        }
        if (!other.getLong().isEmpty()) {
          long_ = other.long_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long oddA_ ;
      /**
       * <code>int64 oddA = 1;</code>
       * @return The oddA.
       */
      public long getOddA() {
        return oddA_;
      }
      /**
       * <code>int64 oddA = 1;</code>
       * @param value The oddA to set.
       * @return This builder for chaining.
       */
      public Builder setOddA(long value) {
        
        oddA_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 oddA = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOddA() {
        
        oddA_ = 0L;
        onChanged();
        return this;
      }

      private long evenA_ ;
      /**
       * <code>int64 evenA = 2;</code>
       * @return The evenA.
       */
      public long getEvenA() {
        return evenA_;
      }
      /**
       * <code>int64 evenA = 2;</code>
       * @param value The evenA to set.
       * @return This builder for chaining.
       */
      public Builder setEvenA(long value) {
        
        evenA_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 evenA = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvenA() {
        
        evenA_ = 0L;
        onChanged();
        return this;
      }

      private int oddB_ ;
      /**
       * <code>int32 oddB = 3;</code>
       * @return The oddB.
       */
      public int getOddB() {
        return oddB_;
      }
      /**
       * <code>int32 oddB = 3;</code>
       * @param value The oddB to set.
       * @return This builder for chaining.
       */
      public Builder setOddB(int value) {
        
        oddB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 oddB = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOddB() {
        
        oddB_ = 0;
        onChanged();
        return this;
      }

      private int evenB_ ;
      /**
       * <code>int32 evenB = 4;</code>
       * @return The evenB.
       */
      public int getEvenB() {
        return evenB_;
      }
      /**
       * <code>int32 evenB = 4;</code>
       * @param value The evenB to set.
       * @return This builder for chaining.
       */
      public Builder setEvenB(int value) {
        
        evenB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 evenB = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvenB() {
        
        evenB_ = 0;
        onChanged();
        return this;
      }

      private float small_ ;
      /**
       * <code>float small = 5;</code>
       * @return The small.
       */
      public float getSmall() {
        return small_;
      }
      /**
       * <code>float small = 5;</code>
       * @param value The small to set.
       * @return This builder for chaining.
       */
      public Builder setSmall(float value) {
        
        small_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float small = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSmall() {
        
        small_ = 0F;
        onChanged();
        return this;
      }

      private float big_ ;
      /**
       * <code>float big = 6;</code>
       * @return The big.
       */
      public float getBig() {
        return big_;
      }
      /**
       * <code>float big = 6;</code>
       * @param value The big to set.
       * @return This builder for chaining.
       */
      public Builder setBig(float value) {
        
        big_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float big = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBig() {
        
        big_ = 0F;
        onChanged();
        return this;
      }

      private Object short_ = "";
      /**
       * <code>string short = 7;</code>
       * @return The short.
       */
      public String getShort() {
        Object ref = short_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          short_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string short = 7;</code>
       * @return The bytes for short.
       */
      public com.google.protobuf.ByteString
          getShortBytes() {
        Object ref = short_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          short_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string short = 7;</code>
       * @param value The short to set.
       * @return This builder for chaining.
       */
      public Builder setShort(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        short_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string short = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearShort() {
        
        short_ = getDefaultInstance().getShort();
        onChanged();
        return this;
      }
      /**
       * <code>string short = 7;</code>
       * @param value The bytes for short to set.
       * @return This builder for chaining.
       */
      public Builder setShortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        short_ = value;
        onChanged();
        return this;
      }

      private Object long_ = "";
      /**
       * <code>string long = 8;</code>
       * @return The long.
       */
      public String getLong() {
        Object ref = long_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          long_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string long = 8;</code>
       * @return The bytes for long.
       */
      public com.google.protobuf.ByteString
          getLongBytes() {
        Object ref = long_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          long_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string long = 8;</code>
       * @param value The long to set.
       * @return This builder for chaining.
       */
      public Builder setLong(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        long_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string long = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLong() {
        
        long_ = getDefaultInstance().getLong();
        onChanged();
        return this;
      }
      /**
       * <code>string long = 8;</code>
       * @param value The bytes for long to set.
       * @return This builder for chaining.
       */
      public Builder setLongBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        long_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xzj.encode.DataItem)
    }

    // @@protoc_insertion_point(class_scope:com.xzj.encode.DataItem)
    private static final DataItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataItem();
    }

    public static DataItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataItem>
        PARSER = new com.google.protobuf.AbstractParser<DataItem>() {
      @Override
      public DataItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataItem> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DataItem> getParserForType() {
      return PARSER;
    }

    @Override
    public DataItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xzj_encode_DataItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xzj_encode_DataItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016dataitem.proto\022\016com.xzj.encode\"}\n\010Data" +
      "Item\022\014\n\004oddA\030\001 \001(\003\022\r\n\005evenA\030\002 \001(\003\022\014\n\004odd" +
      "B\030\003 \001(\005\022\r\n\005evenB\030\004 \001(\005\022\r\n\005small\030\005 \001(\002\022\013\n" +
      "\003big\030\006 \001(\002\022\r\n\005short\030\007 \001(\t\022\014\n\004long\030\010 \001(\tB" +
      "\tB\007DataMsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xzj_encode_DataItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xzj_encode_DataItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xzj_encode_DataItem_descriptor,
        new String[] { "OddA", "EvenA", "OddB", "EvenB", "Small", "Big", "Short", "Long", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
