eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: user-service
#  zipkin:
#    base-url: http://localhost:9411
  ###### 不需要显示设置rabbitmq的默认配置，引入spring-cloud-stream-binder-rabbit-core中的RabbitBindingCleaner会自动设置以下默认配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  sleuth:
    sampler:
      percentage: 1.0

#spring.zipkin.base-url=http://localhost:9411
