eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
  storage:
    type: mysql

#spring.sleuth.sampler.percentage: 1.0