eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: user-service
###### 不需要显示设置zipkin的默认配置，引入spring-cloud-sleuth-zipkin-stream会由类ZipkinProperties自动设置以下默认配置
#  zipkin:
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

#spring.zipkin.base-url=http://localhost:9411
